version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nuts_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  app:
    build: .
    depends_on:
      - db
      - nats
    volumes:
      - .:/app
    environment:
      - NATS_URL=nats://18.234.166.68:4222
      - DATABASE_URL=postgresql://postgres:password@db:5432/nuts_db
    command: ["python", "main.py"]

volumes:
  db_data:
